# Generated by Django 2.0.2 on 2018-02-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(default='title', max_length=200)),
                ('rating', models.CharField(default='rating', max_length=200)),
                ('created_date', models.CharField(default='created_date', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_id', models.CharField(default='webtoon id', max_length=200)),
                ('webtoon_name', models.CharField(default='webtoon name', max_length=200)),
                ('author', models.CharField(default='author', max_length=200)),
                ('description', models.CharField(default='description', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='webtoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Webtoon'),
        ),
    ]
